/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author mylaptop
 */
public class StartScreen extends javax.swing.JFrame {

	/**
	 * Creates new form StartScreen
	 */
	public static boolean isHost;

	public StartScreen() {
		initComponents();
		setBounds(0, 0, 400, 465);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hostBtn = new javax.swing.JButton();
        joinBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        labelIcon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlightJetGame");
        getContentPane().setLayout(null);

        hostBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        hostBtn.setForeground(new java.awt.Color(254, 254, 254));
        hostBtn.setText("Host");
        hostBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 2, true));
        hostBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hostBtn.setOpaque(false);
        hostBtn.setContentAreaFilled(false);
        hostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hostBtn);
        hostBtn.setBounds(150, 220, 120, 40);

        joinBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        joinBtn.setForeground(new java.awt.Color(254, 254, 254));
        joinBtn.setText("Join");
        joinBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 2, true));
        joinBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        joinBtn.setOpaque(false);
        joinBtn.setContentAreaFilled(false);
        joinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinBtnActionPerformed(evt);
            }
        });
        getContentPane().add(joinBtn);
        joinBtn.setBounds(150, 290, 120, 40);

        exitBtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(254, 254, 254));
        exitBtn.setText("Exit");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 2, true));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setOpaque(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn);
        exitBtn.setBounds(150, 360, 120, 40);

        labelIcon.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/assets/logo.png"))); // NOI18N
        getContentPane().add(labelIcon);
        labelIcon.setBounds(40, 10, 340, 150);

        background.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("assets/background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(-1, -3, 420, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
		System.exit(0);
	}//GEN-LAST:event_exitBtnActionPerformed

	private void hostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostBtnActionPerformed
		setHost(true);
		DetailsDialog.display(0);
	}//GEN-LAST:event_hostBtnActionPerformed

    private void joinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinBtnActionPerformed
		setHost(false);
		DetailsDialog.display(1);
    }//GEN-LAST:event_joinBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StartScreen().setVisible(true);
			}
		});
	}

	public static void setHost(boolean i){
		isHost = i;
	}
	
	public static boolean isHost(){
		return isHost;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton hostBtn;
    private javax.swing.JButton joinBtn;
    private javax.swing.JLabel labelIcon;
    // End of variables declaration//GEN-END:variables
}
